import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description: "Premium noise-cancelling headphones with 30-hour battery life",
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    rating: 4.5,
    reviews: 128,
    inStock: true,
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your health and fitness with this advanced smartwatch",
    price: 299.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Wearables",
    rating: 4.3,
    reviews: 89,
    inStock: true,
  },
  {
    id: "3",
    name: "Portable Laptop Stand",
    description: "Ergonomic aluminum laptop stand for better posture",
    price: 49.99,
    originalPrice: 69.99,
    discount: 29,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    rating: 4.7,
    reviews: 203,
    inStock: true,
  },
  {
    id: "4",
    name: "Wireless Charging Pad",
    description: "Fast wireless charging for all Qi-enabled devices",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    rating: 4.2,
    reviews: 156,
    inStock: true,
  },
  {
    id: "5",
    name: "Gaming Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard for gaming enthusiasts",
    price: 129.99,
    originalPrice: 159.99,
    discount: 19,
    image: "/placeholder.svg?height=300&width=300",
    category: "Gaming",
    rating: 4.6,
    reviews: 94,
    inStock: true,
  },
  {
    id: "6",
    name: "USB-C Hub",
    description: "7-in-1 USB-C hub with HDMI, USB 3.0, and SD card slots",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    rating: 4.4,
    reviews: 167,
    inStock: true,
  },
  {
    id: "7",
    name: "Bluetooth Speaker",
    description: "Portable waterproof speaker with 360-degree sound",
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    image: "/placeholder.svg?height=300&width=300",
    category: "Audio",
    rating: 4.5,
    reviews: 112,
    inStock: true,
  },
  {
    id: "8",
    name: "Smartphone Camera Lens Kit",
    description: "Professional lens attachments for mobile photography",
    price: 59.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Photography",
    rating: 4.1,
    reviews: 78,
    inStock: true,
  },
]
